openapi: 3.0.0
info:
  title: "Trail Service API"
  description: "An API for managing trails, features, and users"
  version: "1.0.0"

servers:
  - url: "/api"
    description: "Base URL for the API"

components:
  schemas:
    Trail:
      type: object
      required:
        - Trail_name
        - Difficulty
        - Location
        - Length
        - Elevation_gain
        - Route_type
      properties:
        TrailID:
          type: integer
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
          format: float
        Elevation_gain:
          type: number
          format: float
        Route_type:
          type: string
        OwnerID:
          type: integer

    TrailInput:
      type: object
      properties:
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
        Elevation_gain:
          type: number
        Route_type:
          type: string
        OwnerID:
          type: integer

  parameters:
    trailId:
      name: "trailId"
      in: path
      required: true
      description: "The ID of the trail"
      schema:
        type: integer

paths:
  /trails:
    get:
      operationId: "trails.get_all"
      tags:
        - "Trails"
      summary: "Retrieve all trails"
      responses:
        "200":
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      operationId: "trails.create"
      tags:
        - "Trails"
      summary: "Create a new trail"
      requestBody:
        description: "Data for the new trail"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrailInput"
      responses:
        "201":
          description: "Trail successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"

  /trails/{trailId}:
    get:
      operationId: "trails.get_one"
      tags:
        - "Trails"
      summary: "Retrieve a single trail by ID"
      parameters:
        - $ref: "#/components/parameters/trailId"
      responses:
        "200":
          description: "Trail details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "404":
          description: "Trail not found"
    put:
      operationId: "trails.update"
      tags:
        - "Trails"
      summary: "Update an existing trail"
      parameters:
        - $ref: "#/components/parameters/trailId"
      requestBody:
        description: "Updated data for the trail"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrailInput"
      responses:
        "200":
          description: "Trail successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "404":
          description: "Trail not found"
    delete:
      operationId: "trails.delete"
      tags:
        - "Trails"
      summary: "Delete a trail"
      parameters:
        - $ref: "#/components/parameters/trailId"
      responses:
        "204":
          description: "Trail successfully deleted"
        "404":
          description: "Trail not found"
